export const ANSWER_WORDS = [
  'ADORE', 'BLOOM', 'BRICK', 'CLOUD', 'CRANE', 'DREAM', 'EMBER', 'FLAME',
  'FOCUS', 'GLOWY', 'GRACE', 'HONEY', 'IVORY', 'JOLLY', 'LEMON', 'LILAC',
  'LUNAR', 'MAPLE', 'MIRTH', 'NOBLE', 'OCEAN', 'OLIVE', 'PEARL', 'PIANO',
  'PLUME', 'PRISM', 'QUILT', 'RAVEN', 'RIVER', 'ROBIN', 'SABLE', 'SHINE',
  'SOLAR', 'SPARK', 'STONE', 'SUNNY', 'TIGER', 'UNION', 'VIVID', 'WALTZ',
  'WATER', 'WORTH', 'YOUNG', 'ZEBRA',
]

export const VALID_WORDS = [
  ...ANSWER_WORDS,
  'ABOVE', 'AGILE', 'ALERT', 'ANGEL', 'APPLE', 'ARISE', 'AUDIO', 'BEACH',
  'BLEND', 'BLINK', 'BRAVE', 'BREAD', 'BRUSH', 'CANDY', 'CHARM',
  'CHIME', 'CIDER', 'CIVIC', 'CLEAR', 'CLIMB', 'COAST', 'COLOR', 'CORAL',
  'CROWN', 'DANCE', 'DELTA', 'EARTH', 'EASEL', 'ECHOE', 'FAITH', 'FANCY',
  'FABLE', 'FEAST', 'FRESH', 'FROST', 'GIANT', 'GHOST', 'GRAIN', 'HAPPY',
  'HEART', 'HOUSE', 'IDEAL', 'INDEX', 'JEWEL', 'KNEEL', 'KNACK', 'LAYER',
  'LIGHT', 'MAGIC', 'MAJOR', 'METAL', 'MIGHT', 'MONEY', 'MOOSE', 'MOTOR',
  'MUSIC', 'NERVE', 'NIGHT', 'NURSE', 'OPERA', 'OTHER', 'PAINT', 'PARTY',
  'PEACH', 'PEACE', 'PENNY', 'PILOT', 'PIXEL', 'PLANT', 'POINT', 'POWER',
  'PULSE', 'QUEEN', 'QUICK', 'RADIO', 'REACT', 'RELAX', 'ROUTE', 'ROYAL',
  'SAUCE', 'SCALE', 'SCENE', 'SCOPE', 'SHEEP', 'SHELF', 'SILKY', 'SKATE',
  'SLATE', 'SMILE', 'SNAKE', 'SOUND', 'SOUTH', 'SPACE', 'SPORE', 'SUGAR',
  'SWEET', 'TABLE', 'TEACH', 'THANK', 'THINK', 'TOAST', 'TRAIN', 'TRAIL',
  'TRUST', 'ULTRA', 'VALUE', 'VOICE', 'WHALE', 'WHEAT', 'WHITE', 'WORLD',
  'WRITE', 'YEARN', 'YIELD', 'ZESTY',
]
